

deploy:
	dotnet build
	mkdir -p ~/".config/unity3d/Klei/Oxygen Not Included/mods/Dev/EarlyGameNosh"
	cp bin/Debug/net471/early_game_nosh.dll ~/".config/unity3d/Klei/Oxygen Not Included/mods/Dev/EarlyGameNosh/" -v
	cp mod_info.yaml ~/".config/unity3d/Klei/Oxygen Not Included/mods/Dev/EarlyGameNosh/" -v
	cp mod.yaml ~/".config/unity3d/Klei/Oxygen Not Included/mods/Dev/EarlyGameNosh/" -v
