

deploy:
	dotnet build
	mkdir -p ~/".config/unity3d/Klei/Oxygen Not Included/mods/Dev/OrbitalScienceFix"
	cp bin/Debug/net471/orbital_science_fix.dll ~/".config/unity3d/Klei/Oxygen Not Included/mods/Dev/OrbitalScienceFix/" -v
	cp mod_info.yaml ~/".config/unity3d/Klei/Oxygen Not Included/mods/Dev/OrbitalScienceFix/" -v
	cp mod.yaml ~/".config/unity3d/Klei/Oxygen Not Included/mods/Dev/OrbitalScienceFix/" -v
